AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  vcat-backend

  Sample SAM Template for vcat-backend

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    CodeUri: src/

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
Resources:
  ControlsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: functions.controls.main.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        GetControls:
          Type: Api
          Properties:
            Path: /controls
            Method: get
        GetControlById:
          Type: Api
          Properties:
            Path: /controls/{vgcpid}
            Method: get
        CreateControl:
          Type: Api
          Properties:
            Path: /controls
            Method: post
        UpdateControl:
          Type: Api
          Properties:
            Path: /controls/{vgcpid}
            Method: put

  CatalogFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: functions.catalog.main.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        GetCatalog:
          Type: Api
          Properties:
            Path: /catalog
            Method: get

  RequestsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: functions.requests.main.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        GetRequests:
          Type: Api
          Properties:
            Path: /requests
            Method: get

  CommentsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: functions.comments.main.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        GetComments:
          Type: Api
          Properties:
            Path: /comments
            Method: get

  AuditFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: functions.audit.main.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        GetAudit:
          Type: Api
          Properties:
            Path: /audit
            Method: get

  ExportFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: functions.exporting.main.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        ExportApi:
          Type: Api
          Properties:
            Path: /export
            Method: get

  NotificationsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: functions.notifications.main.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        GetNotifications:
          Type: Api
          Properties:
            Path: /notifications
            Method: get

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: "true"
# Outputs:
#   # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
#   # Find out more about other implicit resources you can reference within SAM
#   # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
#   HelloWorldApi:
#     Description: API Gateway endpoint URL for Prod stage for Hello World
#       function
#     Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/hello/"
#   HelloWorldFunction:
#     Description: Hello World Lambda Function ARN
#     Value: !GetAtt HelloWorldFunction.Arn
#   HelloWorldFunctionIamRole:
#     Description: Implicit IAM Role created for Hello World function
#     Value: !GetAtt HelloWorldFunctionRole.Arn
